### ISSUE TITLE
Whip data

### ISSUE THREAD

**Issue by peterdesmet** [inbo/muskrat-rato-occurrences#5]
- [x] individualCount: 64 max?
- [x] individualCount: sometimes 0 for occurrenceRemarks "catch"
- [x] datasetName: "Mica Rato Muskrat Occurrences in East Flanders, Belgium" Cf other dataset, I don't think Mica should be in title? Would choose: `RATO - Muskrat occurrences in East Flanders, Belgium`
- [x] samplingProtocol: is it necessary to indicate the number of traps (which is effort), rather than just the type of trap?
- [x] samplingEffort: use `:` instead of `=`
- [x] eventDate: month should be written with 2 characters `02`, not `2018-2-20`
- [x] verbatimLatitude/verbatimLongitude: are the original coordinates recorded by the app lambert coordinates? If not, I would drop the verbatim fields
- [x] verbatimLatitude/verbatimLongitude: no decimals
- [x] verbatimCoordinateSystem: Belgian Datum **19**72
- [x] decimalLat/Long: only 5 decimals
- [x] identifiedBy/recordedBy: RATO, not Rato
- [x] kingdom: Animalia, not Animal
- [x] status: rename to "occurrenceStatus", place after individualCount
- [x] taxonRank: add right before nomenclaturalCode, with value `species`

**Comment by DimEvil** [comment]
- [ ] individualCount: 64 max?
There is no fixed max number of rats trapped. Actually, I don't think there should be a maximum number. Or this should be defined by the data curator. 
- [ ] individualCount: sometimes 0 for occurrenceRemarks "catch"
This reflects the data, there are not so much validation steps in the app, I guess
- [ ] datasetName: "Mica Rato Muskrat Occurrences in East Flanders, Belgium" Cf other dataset, I don't think Mica should be in title? Would choose: `RATO - Muskrat occurrences in East Flanders, Belgium`
I'm in favor of adding the project acronym in the title, this is a decision to be made 
- [ ] samplingProtocol: is it necessary to indicate the number of traps (which is effort), rather than just the type of trap?
The effort is the number of times a trap was visited. I think.
- [ ] samplingEffort: use `:` instead of `=`
- [ ] eventDate: month should be written with 2 characters `02`, not `2018-2-20`

- [ ] verbatimLatitude/verbatimLongitude: are the original coordinates recorded by the app lambert coordinates? If not, I would drop the verbatim fields
yes, they are
- [ ] verbatimLatitude/verbatimLongitude: no decimals
- [ ] verbatimCoordinateSystem: Belgian Datum **19**72
- [ ] decimalLat/Long: only 5 decimals
- [ ] identifiedBy/recordedBy: RATO, not Rato
- [ ] kingdom: Animalia, not Animal
- [ ] status: rename to "occurrenceStatus", place after individualCount
- [ ] taxonRank: add right before nomenclaturalCode, with value `species`

**Comment by peterdesmet** [comment]
- [ ] `datasetName`: now of form "Mica Rato Muskrat Occurrences in East Flanders, Belgium". Following dataset capitalization, it should at least be `MICA/RATO - Muskrat occurrences in East Flanders, Belgium`. We decided not to include the project name for https://ipt.inbo.be/resource?r=mica-legacy-occurrences, so I'd either opt for:

        RATO - Muskrat occurrences in East Flanders, Belgium
        MICA - Muskrat occurrences collected by RATO in East Flanders, Belgium

- [ ] Some `decimalLat/Long` have less than .5 decimals

- [x] individualCount: I have removed max
- [x] individualCount: I now only that that `0` should have `absent`, which passes test
- [ ] recordedBy: update to `RATO` (was only corrected for `identifiedBy`
- [ ] verbatimCoordinateSystem: my mistake, this should have remained `Lambert coordinates`
- [ ] verbatimSRS however, should be `Belgian Datum 1972`

**Comment by peterdesmet** [comment]
Data passed validation! 🥳
